name: yolov5
dependencies:
  - pip=21.2.2
  - python=3.7.6
  - numpy=1.20.3
  - pillow=8.3.1
  - pyyaml=5.4.1
  - scipy=1.7.1
  - pytorch::pytorch=1.9.0
  - pytorch::torchvision=0.10.0
  - nvidia::cudatoolkit=11.1
